#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TMP="$(mktemp -d -t clinch-release-stage-test)"
trap 'rm -rf "$TMP"' EXIT
FIXTURE="$TMP/repo"
RELEASE_DIR="$FIXTURE/target/release-lto/bundle/osx"
ARM64_APP="$FIXTURE/target/aarch64-apple-darwin/release-lto/bundle/osx/Clinch.app"
X86_64_APP="$FIXTURE/target/x86_64-apple-darwin/release-lto/bundle/osx/Clinch.app"
mkdir -p \
  "$FIXTURE/script" \
  "$FIXTURE/resources/release" \
  "$FIXTURE/resources/update" \
  "$FIXTURE/web/remote-control/.yarn/releases" \
  "$RELEASE_DIR" \
  "$ARM64_APP" \
  "$X86_64_APP" \
  "$TMP/bin"
cp \
  "$ROOT/script/assemble-clinch-release-stage" \
  "$ROOT/script/verify-clinch-release-stage" \
  "$ROOT/script/verify-clinch-source-archive" \
  "$ROOT/script/clinch-update-manifest" \
  "$FIXTURE/script/"
cp "$ROOT/Cargo.lock" "$FIXTURE/Cargo.lock"
cp "$ROOT/LICENSE-AGPL" "$ROOT/LICENSE-MIT" "$ROOT/NOTICE" "$FIXTURE/"
printf '[workspace]\nmembers = []\n' > "$FIXTURE/Cargo.toml"
printf '#!/bin/sh\n' > "$FIXTURE/install.sh"
printf '#!/bin/sh\n' > "$FIXTURE/uninstall.sh"
cat > "$FIXTURE/web/remote-control/package.json" <<'EOF'
{
  "name": "clinch-stage-fixture-web",
  "version": "0.1.0",
  "private": true,
  "packageManager": "yarn@4.18.0"
}
EOF
cat > "$FIXTURE/web/remote-control/yarn.lock" <<'EOF'
# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
EOF
printf 'yarnPath: .yarn/releases/yarn-4.18.0.cjs\n' \
  > "$FIXTURE/web/remote-control/.yarnrc.yml"
printf '// Yarn release stand-in for the release-stage fixture.\n' \
  > "$FIXTURE/web/remote-control/.yarn/releases/yarn-4.18.0.cjs"

VERSION=v0.2099.01.02.0304
COMMIT=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
SEQUENCE=4102441440

find_openssl3() {
  local candidate
  for candidate in "${CLINCH_OPENSSL_BIN:-}" "$(command -v openssl 2>/dev/null || true)" \
      /opt/homebrew/opt/openssl@3/bin/openssl /usr/local/opt/openssl@3/bin/openssl; do
    [[ -n "$candidate" && -x "$candidate" ]] || continue
    if "$candidate" version 2>/dev/null | grep -q '^OpenSSL 3\.'; then
      printf '%s\n' "$candidate"
      return
    fi
  done
  echo "SKIP: OpenSSL 3 is unavailable" >&2
  exit 0
}

OPENSSL3="$(find_openssl3)"
export CLINCH_OPENSSL_BIN="$OPENSSL3"

"$OPENSSL3" genpkey -algorithm Ed25519 -out "$TMP/update-key.pem"
update_public="$($OPENSSL3 pkey -in "$TMP/update-key.pem" -pubout -outform DER \
  | tail -c 32 | base64 | tr -d '\n')"
printf '{"ed25519_public_key":"%s","key_id":"fixture"}\n' "$update_public" \
  > "$FIXTURE/resources/update/clinch-update-public-key.json"
"$FIXTURE/script/clinch-update-manifest" verify-key \
  "$TMP/update-key.pem" "$FIXTURE/resources/update/clinch-update-public-key.json" >/dev/null
"$OPENSSL3" genpkey -algorithm Ed25519 -out "$TMP/wrong-update-key.pem"
if "$FIXTURE/script/clinch-update-manifest" verify-key \
    "$TMP/wrong-update-key.pem" "$FIXTURE/resources/update/clinch-update-public-key.json" \
    > "$TMP/wrong-update-key.out" 2>&1; then
  echo "FAIL: mismatched update signing key was accepted" >&2
  exit 1
fi

ssh-keygen -q -t ed25519 -N '' -f "$TMP/release-key"
printf 'clinch-release %s\n' "$(awk '{print $1, $2}' "$TMP/release-key.pub")" \
  > "$FIXTURE/resources/release/clinch-release-allowed-signers"

printf 'fixture zip\n' > "$RELEASE_DIR/Clinch.app.zip"
printf 'fixture dmg\n' > "$RELEASE_DIR/Clinch.dmg"
printf 'fixture Intel zip\n' > "$RELEASE_DIR/Clinch-x86_64.app.zip"
printf 'fixture Intel dmg\n' > "$RELEASE_DIR/Clinch-x86_64.dmg"
(cd "$RELEASE_DIR" && shasum -a 256 Clinch.app.zip > Clinch.app.zip.sha256)
(cd "$RELEASE_DIR" && shasum -a 256 Clinch.dmg > Clinch.dmg.sha256)
(cd "$RELEASE_DIR" && shasum -a 256 Clinch-x86_64.app.zip \
  > Clinch-x86_64.app.zip.sha256)
(cd "$RELEASE_DIR" && shasum -a 256 Clinch-x86_64.dmg \
  > Clinch-x86_64.dmg.sha256)

/usr/bin/python3 - "$RELEASE_DIR" "$VERSION" "$SEQUENCE" <<'PY'
import hashlib
import json
import pathlib
import sys

release_dir = pathlib.Path(sys.argv[1])
version = sys.argv[2]
sequence = int(sys.argv[3])
archive = release_dir / "Clinch.app.zip"
intel_archive = release_dir / "Clinch-x86_64.app.zip"

def record(path):
    return {
        "name": path.name,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "size": path.stat().st_size,
        "url": (
            "https://github.com/elliot-ylambda/clinch-terminal/releases/download/"
            f"{version}/{path.name}"
        ),
    }

arm64_record = record(archive)
manifest = {
    "architectures": ["arm64", "x86_64"],
    "archive": arm64_record,
    "archives": {"arm64": arm64_record, "x86_64": record(intel_archive)},
    "bundle_id": "sh.clinch.Clinch",
    "minimum_macos_version": "14.0",
    "notarized": False,
    "release_notes": "Fixture release notes.",
    "release_url": (
        "https://github.com/elliot-ylambda/clinch-terminal/releases/tag/"
        f"{version}"
    ),
    "repository": "elliot-ylambda/clinch-terminal",
    "rollback": False,
    "schema_version": 1,
    "sequence": sequence,
    "signing_key_id": "fixture",
    "tag": version,
    "version": version,
}
(release_dir / "Clinch.update.json").write_text(
    json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n",
    encoding="utf-8",
)
PY

"$OPENSSL3" pkeyutl -sign -rawin -inkey "$TMP/update-key.pem" \
  -in "$RELEASE_DIR/Clinch.update.json" -out "$TMP/update-signature.bin"
base64 < "$TMP/update-signature.bin" | tr -d '\n' > "$RELEASE_DIR/Clinch.update.sig"
printf '\n' >> "$RELEASE_DIR/Clinch.update.sig"
ssh-keygen -Y sign -f "$TMP/release-key" -n clinch-install - \
  < "$RELEASE_DIR/Clinch.update.json" > "$RELEASE_DIR/Clinch.update.sshsig"

cat > "$TMP/bin/git" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ "$*" == 'rev-parse HEAD' ]] || exit 2
printf '%s\n' "$FIXTURE_COMMIT"
STUB

cat > "$TMP/bin/sw_vers" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == -productVersion ]] || exit 2
printf '%s\n' '99.0'
STUB

cat > "$TMP/bin/syft" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ "$2" == -o && "$3" == cyclonedx-json=* ]] || exit 2
output="${3#cyclonedx-json=}"
printf '{"bomFormat":"CycloneDX","specVersion":"1.6"}\n' > "$output"
STUB

# Source-archive verification reinstalls the web dependencies offline. The
# fixture carries a stand-in Yarn cache rather than a real dependency graph, so
# the install is stubbed the same way git, sw_vers, and syft are above.
cat > "$TMP/bin/corepack" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == yarn ]] || { echo "unexpected corepack command: $*" >&2; exit 2; }
cwd=.
previous=
for argument in "$@"; do
  [[ "$previous" == --cwd ]] && cwd="$argument"
  previous="$argument"
done
case " $* " in
  *' install '*)
    mkdir -p "$cwd/.yarn/cache" "$cwd/node_modules"
    printf 'fixture package archive\n' \
      > "$cwd/.yarn/cache/fixture-npm-1.0.0-fixture-8.zip"
    printf 'fixture install state\n' > "$cwd/.yarn/install-state.gz"
    ;;
  *)
    echo "unexpected yarn command: $*" >&2
    exit 2
    ;;
esac
STUB

cat > "$FIXTURE/script/assemble-clinch-corresponding-source" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
version="$1"
commit="$2"
output="$3"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
name="Clinch-${version#v}-source"
root="$work/$name"
vendor_id=0000000000000000
mkdir -p "$root/.cargo" "$root/vendor/$vendor_id/fixture-1.0.0" \
  "$root/web/remote-control/.yarn/releases" "$root/web/remote-control/.yarn/cache"
cp Cargo.toml Cargo.lock LICENSE-AGPL LICENSE-MIT NOTICE "$root/"
cp web/remote-control/package.json web/remote-control/yarn.lock \
  web/remote-control/.yarnrc.yml "$root/web/remote-control/"
cp web/remote-control/.yarn/releases/yarn-4.18.0.cjs \
  "$root/web/remote-control/.yarn/releases/"
printf 'fixture package archive\n' \
  > "$root/web/remote-control/.yarn/cache/fixture-npm-1.0.0-fixture-8.zip"
cat > "$root/.cargo/config.toml" <<EOF
[source.crates-io]
replace-with = "clinch-vendor-$vendor_id"

[source."clinch-vendor-$vendor_id"]
directory = "vendor/$vendor_id"
EOF
printf '{}\n' > "$root/vendor/$vendor_id/fixture-1.0.0/.cargo-checksum.json"
printf '# %s Corresponding Source\n\n%s\n\ncargo metadata --offline\n%s\n' \
  "$version" "$commit" \
  'YARN_ENABLE_NETWORK=0 corepack yarn --cwd web/remote-control install --immutable --immutable-cache' \
  > "$root/CORRESPONDING_SOURCE.md"
/usr/bin/python3 - "$root/.clinch-source.json" "$version" "$commit" Cargo.lock \
  web/remote-control/yarn.lock <<'PY'
import hashlib
import json
import pathlib
import sys

pathlib.Path(sys.argv[1]).write_text(json.dumps({
    "cargo_lock_sha256": hashlib.sha256(pathlib.Path(sys.argv[4]).read_bytes()).hexdigest(),
    "commit": sys.argv[3],
    "schema_version": 2,
    "version": sys.argv[2],
    "yarn_lock_sha256": hashlib.sha256(pathlib.Path(sys.argv[5]).read_bytes()).hexdigest(),
}, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
PY
COPYFILE_DISABLE=1 tar -czf "$output" -C "$work" "$name"
(cd "$(dirname "$output")" && shasum -a 256 "$(basename "$output")" \
  > "$(basename "$output").sha256")
STUB
chmod +x "$FIXTURE/script/"* "$TMP/bin/"*

assemble_output="$(cd "$FIXTURE" && env \
  PATH="$TMP/bin:$PATH" \
  FIXTURE_COMMIT="$COMMIT" \
  CLINCH_RELEASE_SIGNING_KEY="$TMP/release-key" \
  ./script/assemble-clinch-release-stage \
    "$VERSION" "$COMMIT" "$SEQUENCE")"
grep -Fq "target/release-stage/$VERSION" <<< "$assemble_output"

DIST="$FIXTURE/target/release-stage/$VERSION/dist"
[[ -f "$FIXTURE/target/release-stage/$VERSION/release-notes.md" ]]
/usr/bin/python3 - "$DIST/Clinch.release-validation.json" <<'PY'
import json
import pathlib
import sys

validation = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
assert validation["schema_version"] == 5
assert validation["release_layout"] == "native"
assert "manual_qa" not in validation
PY

verify() {
  (cd "$FIXTURE" && PATH="$TMP/bin:$PATH" ./script/verify-clinch-release-stage "$@")
}

verify_universal() {
  (cd "$FIXTURE" && PATH="$TMP/bin:$PATH" UNIVERSAL=1 \
    ./script/verify-clinch-release-stage "$@")
}

expect_failure() {
  local label="$1"
  shift
  if "$@" >"$TMP/$label.out" 2>"$TMP/$label.err"; then
    echo "FAIL: $label was accepted" >&2
    exit 1
  fi
}

verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE" >/dev/null

cp "$DIST/Clinch.app.zip" "$TMP/Clinch.app.zip"
printf 'tampered\n' >> "$DIST/Clinch.app.zip"
expect_failure tampered verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
cp "$TMP/Clinch.app.zip" "$DIST/Clinch.app.zip"

cp "$DIST/Clinch-x86_64.app.zip" "$TMP/Clinch-x86_64.app.zip"
printf 'tampered\n' >> "$DIST/Clinch-x86_64.app.zip"
expect_failure tampered_intel verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
cp "$TMP/Clinch-x86_64.app.zip" "$DIST/Clinch-x86_64.app.zip"

expect_failure wrong_layout verify_universal \
  "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"

cp "$DIST/Clinch.source.tar.gz" "$TMP/Clinch.source.tar.gz"
printf 'tampered\n' >> "$DIST/Clinch.source.tar.gz"
expect_failure tampered_source verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
cp "$TMP/Clinch.source.tar.gz" "$DIST/Clinch.source.tar.gz"

printf 'extra\n' > "$DIST/unexpected.txt"
expect_failure extra verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
rm "$DIST/unexpected.txt"

mkdir "$DIST/unexpected-directory"
expect_failure extra_directory verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
rmdir "$DIST/unexpected-directory"

mv "$DIST/uninstall.sh" "$TMP/uninstall.sh"
expect_failure missing verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
mv "$TMP/uninstall.sh" "$DIST/uninstall.sh"

expect_failure wrong_version verify "$DIST" v0.2099.01.02.0305 "$COMMIT" "$SEQUENCE"
expect_failure wrong_commit verify "$DIST" "$VERSION" bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb "$SEQUENCE"
expect_failure stale_sequence verify "$DIST" "$VERSION" "$COMMIT" "$((SEQUENCE - 1))"

cp "$DIST/Clinch.build-provenance.sshsig" "$TMP/provenance.sshsig"
printf 'invalid\n' > "$DIST/Clinch.build-provenance.sshsig"
expect_failure invalid_signature verify "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE"
cp "$TMP/provenance.sshsig" "$DIST/Clinch.build-provenance.sshsig"

# The explicit legacy flag still assembles and verifies the smaller, original
# universal asset set without carrying stale native-mode files into the draft.
mkdir -p "$RELEASE_DIR/Clinch.app"
/usr/bin/python3 - "$RELEASE_DIR/Clinch.update.json" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
manifest = json.loads(path.read_text(encoding="utf-8"))
manifest.pop("archives")
path.write_text(
    json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n",
    encoding="utf-8",
)
PY
"$OPENSSL3" pkeyutl -sign -rawin -inkey "$TMP/update-key.pem" \
  -in "$RELEASE_DIR/Clinch.update.json" -out "$TMP/update-signature.bin"
base64 < "$TMP/update-signature.bin" | tr -d '\n' > "$RELEASE_DIR/Clinch.update.sig"
printf '\n' >> "$RELEASE_DIR/Clinch.update.sig"
ssh-keygen -Y sign -f "$TMP/release-key" -n clinch-install - \
  < "$RELEASE_DIR/Clinch.update.json" > "$RELEASE_DIR/Clinch.update.sshsig"
(cd "$FIXTURE" && env \
  PATH="$TMP/bin:$PATH" \
  FIXTURE_COMMIT="$COMMIT" \
  CLINCH_RELEASE_SIGNING_KEY="$TMP/release-key" \
  UNIVERSAL=1 \
  ./script/assemble-clinch-release-stage "$VERSION" "$COMMIT" "$SEQUENCE" \
  >/dev/null)
verify_universal "$DIST" "$VERSION" "$COMMIT" "$SEQUENCE" >/dev/null
[[ ! -e "$DIST/Clinch-x86_64.app.zip" ]]

echo "PASS"
